### ISSUE TITLE
negative indentation for current line

### ISSUE THREAD

**Issue by expipiplus1** [quchen/prettyprinter#57] opened 2018-04-22 02:18 UTC
I'm generating some code which includes preprocessor macros which must begin on column 0.

It would be nice to be able to do:

```haskell
guarded :: Text -> Doc () -> Doc ()
guarded g d = vcat
  [ indent minBound $ "#if defined(" <> pretty g <> ")"
  , d
  , indent minBound "#endif"
  ]
```

This obviously doesn't work because the negative indent could "reverse" over existing text. However it would be nice to have some kind of primitive which can "deindent" the current line as long as it's just erasing spaces.

This probably doesn't fit in the existing renderer at all though!

**Comment by quchen** [comment] 2018-04-25 21:04
Does this do what you want?

```haskell
unNest :: Doc ann -> Doc ann
unNest doc = nesting (\n -> nest (- n) doc)
```

And then

```haskell
guarded macro doc = vcat
    [ unNest "#if defined(" <> pretty macro <> ")"
    , doc
    , unNest "#endif" ]
```

**Comment by expipiplus1** [comment] 2018-05-08 14:16
Sadly this doesn't work. I'm calling it along the lines of 

```
foo = "   " <> indent 0 (guarded bar baz)
```

So the negative indentation has to remove spaces from the first line, and override the `indent 0` surrounding everything

**Comment by quchen** [comment] 2018-05-11 10:26
The leading spaces are not recognized by the document – they are simply a string of characters that just happen to be non-printable, so they don’t increase the current nesting level. Therefore, »un-nesting« with `-n` levels won’t work. Can’t you use `nest 4` instead of `"␣␣␣␣" <>`?

**Comment by quchen** [comment] 2019-06-15 09:25
I’m closing this as old and probably obsolete by now. If the issue is still relevant, feel free to reopen it.

**Closed by quchen** 2019-06-15 09:25 UTC
Labels: Feature request, Question or comment
