### ISSUE TITLE
Avoid trailing whitespace when aligning empty lines

### ISSUE THREAD

**Issue by purcell** [quchen/prettyprinter#46] opened 2017-11-29 20:35 UTC
Hi! I'm using Dhall, and `dhall-format` is built using `prettyprinter`. Using the `align` function leads to trailing whitespace when empty lines are aligned, as in the example at https://github.com/dhall-lang/dhall-haskell/issues/183.

It's picky, to be sure, but (at least) my brain associates "pretty" with "tidy", so I wonder if it would be straightforward to avoid this case?

**Comment by quchen** [comment] 2017-11-29 22:25
The problem is certainly valid! The solution however is not that straightforward, since an aligned empty line is actually alignment plus a later added newline. 

The simplest solution would probably be another pass over the SimpleDocStream, but that sounds bolted on. I'll try to think of something better!

**Comment by quchen** [comment] 2017-11-30 13:08
I see a big problem with deleting empty lines: they might be annotated! An empty line of 8 spaces with red background is something different than just an empty line. So in general, we cannot delete »indented newlines«, and thus the layout algorithms cannot simply discard them. I guess a separate step, similar to `fuse`, might be the only way to handle this.

**Comment by quchen** [comment] 2018-05-11 12:13
I’m closing this as »won’t fix« – a separate pass over the generated SimpleDoc can be used to achieve the desired functionality, but at the cost of, well, another pass over the SimpleDoc.

**Closed by quchen** 2018-05-11 12:13 UTC

**Comment by bwbaugh** [comment] 2018-05-11 16:09
fwiw, I’m getting trailing whitespace on non empty lines as well. I planned on opening a separate issue when I had time to come up with a minimal example, but…Anyway, we can probably post process with `sed`/`awk` to get rid of the trailing whitespace.

**Comment by quchen** [comment] 2018-05-12 21:57
Interesting, do you have an example of trailing whitespace that’s not on an empty line?

**Comment by Gabriel439** [comment] 2018-05-12 21:58
@quchen: `dhall` supports multi-line string literals, which can have trailing whitespace

**Comment by bwbaugh** [comment] 2018-05-13 00:59
I will try to get an example to you tomorrow. I am fairly sure that I experienced the issue without string literals, or at least definitely not multiline literals.

**Comment by quchen** [comment] 2018-05-13 18:30
@Gabriel439 @bwbaugh Thanks for the pointers! I’m not terribly concerned about (potentially useful because annotated) empty lines, but proper trailing whitespace doesn’t seem like something I would want.

**Comment by bwbaugh** [comment] 2018-05-13 20:18
@quchen , @Gabriel439: Here’s a somewhat minimal example of the trailing whitespace issue on non empty lines:

```bash
$ cat test.dhall
{ foo = ./bar.dhall, qux = "12345678901234567890123456789012345678901234567890" } : ./baz.dhall
$ <test.dhall dhall-format
  { foo =
      ./bar.dhall 
  , qux =
      "12345678901234567890123456789012345678901234567890"
  }
: ./baz.dhall 
$ <test.dhall dhall-format | tr ' ' '␣'
␣␣{␣foo␣=
␣␣␣␣␣␣./bar.dhall␣
␣␣,␣qux␣=
␣␣␣␣␣␣"12345678901234567890123456789012345678901234567890"
␣␣}
:␣./baz.dhall␣
$ dhall-format --version
1.11.1
```

**Comment by quchen** [comment] 2018-06-15 07:20
Good news everyone @purcell @bwbaugh @Gabriel439, I just implemented a function to trim trailing whitespace (https://github.com/quchen/prettyprinter/commit/46626c0e74f9f8cb792d816ca7a28921430e4f20). It’s quite a bit more complex to do this, and to be frank the code isn’t very pretty, but there you go!

**Comment by sjakobi** [comment] 2020-07-21 17:14
Note that https://github.com/quchen/prettyprinter/pull/139 has tweaked the layout algorithms to avoid producing trailing whitespace on indented empty lines. Using `removeTrailingWhitespace` will no longer be necessary for these cases.
