### ISSUE TITLE
Inconsistent formatting within align

### ISSUE THREAD

**Issue by sjakobi** [quchen/prettyprinter#83] opened 2019-10-11 01:21 UTC
If you clone https://github.com/sjakobi/dhall-issue1400 and run the following command within `stack repl`, you should see:

```haskell
> putStrLn $ renderString $ layoutSmart defaultLayoutOptions $ prettyE sample
[ [ [ 0
    ]
  , [ 0 ]
  , [ 111111111111111111111111111111111111111111111111111111111111111111111111111
    ]
  ]
]
```

The problem is that the first `[ 0 ]` is incorrectly formatted with a line break, while the second `[ 0 ]` is formatted correctly on a single line. The correct formatting would be this:

```haskell
[ [ [ 0 ]
  , [ 0 ]
  , [ 111111111111111111111111111111111111111111111111111111111111111111111111111
    ]
  ]
]
```

Note that one of the `align`ed elements must exceed the page width to trigger the malformatting of the first element.

**Comment by sjakobi** [comment] 2019-10-11 14:37
I've simplified the reproducer a bit further. The interesting part is this version of `list`:

```haskell
list' :: [Doc a] -> Doc a
list' docs =
    group
        (flatAlt
            (align ((mconcat (map combineLong  docs'))          <> rbracket))
            (        mconcat (map combineShort docs')  <> space <> rbracket))
  where
    docs' = zip ((lbracket <> space) : repeat (comma <> space)) docs

    combineLong (x, y) = x <> y <> hardline

    combineShort (x, y) = x <> y
```

The full code is [here](https://github.com/sjakobi/dhall-issue1400/blob/master/src/Lib.hs).

**Comment by sjakobi** [comment] 2019-10-11 18:27
Turns out the inconsistency can also be demonstrated with the default `list`:

```
[ [ [ 0 ]
  , [0]
  , [ 111111111111111111111111111111111111111111111111111111111111111111111111111 ] ] ]
```

**Comment by sjakobi** [comment] 2019-10-11 18:54
Finally "die Kür" ;)

```haskell
> e = list []
> d = list [ align (list [ e, e, list [ e ] ]) ]
> opts = defaultLayoutOptions{ layoutPageWidth = AvailablePerLine 10 1 }
> putStrLn $ renderString $ layoutSmart opts d
[ [ [  ]
  , []
  , [ [  ] ] ] ]

**Comment by sjakobi** [comment] 2019-10-12 17:13
Here is a simpler demonstration:

```
> x = group (flatAlt "Default" "Fallback")
> d = "/" <> align (cat [x, x, "Too wide!!!"])
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ d
/Default
 Fallback
 Too wide!!!
```

Since `x` is `group`ed, the output _should_ be:

```
/Fallback
 Fallback
 Too wide!!!
```

**Comment by sjakobi** [comment] 2019-10-16 11:05
Here's the internal structure of `d` from above. I still haven't figured out how and why the first element of an `align` is treated specially in `layoutWadlerLeijen`.

```haskell
Cat
  (Char '/')
  (Column
    (\k ->
      Nesting
        (\i ->
          Nest
            (k - i)
            (Union
              (Cat
                (Text 8 "Fallback")
                (Cat
                  (Text 8 "Fallback")
                  (Text 11 "Too wide!!!")))
              (Cat
                (Union
                  (Text 8 "Fallback")
                  (FlatAlt
                    (Text 7 "Default")
                    (Text 8 "Fallback")))
                (Cat
                  (FlatAlt Line Empty)
                  (Cat
                    (Union
                      (Text 8 "Fallback")
                      (FlatAlt
                        (Text 7 "Default")
                        (Text 8 "Fallback")))
                    (Cat
                      (FlatAlt Line Empty)
                      (Text 11 "Too wide!!!")))))))))
```

**Comment by sjakobi** [comment] 2019-10-18 12:13
@quchen I think that regression test will start failing once you limit the line length to 11 characters – the last line has 12 characters in total.

**Comment by quchen** [comment] 2019-10-18 12:21
It’s failing right now already, hence the commit message

**Comment by sjakobi** [comment] 2019-10-18 12:33
> It’s failing right now already, hence the commit message.

Oh sorry, I misread the test and was surprised by CI being green.

Why is `expected = "/Default\n Default\n Too wide!!!!!"` though? Shouldn't it  be

    "/Fallback\n Fallback\n Too wide!!!!!"

?

**Comment by quchen** [comment] 2019-10-18 13:43
Yes, that’s strange too – it’s not just wrong, it’s inconsistently wrong! At least in the `layoutSmart` case.

I noticed that »fallback« is longer than »default«, but `flatAlt` would like the first line of the alternative to be shorter than the default. But changing the fallback to »fall« didn’t change the behavior, so I guess that’s not it.

**Comment by sjakobi** [comment] 2019-10-18 13:49
> I noticed that »fallback« is longer than »default«, but `flatAlt` would like the first line of the alternative to be shorter than the default

Right. I had been wondering which part of the code actually relies on that.

BTW if it's unclear when this issue can be fixed, it would be nice to get a release of the fixes of #84 and #86 first.

**Comment by quchen** [comment] 2019-10-18 15:42
I’m on track to finding the cause of this, and I think it’s in a way the desired behavior. Unfortunately, it’s also surprising, which makes fixing it a bit harder. I think I’ll go with a release before fixing this.


# Explanation sketch

I haven’t sorted my thoughts just yet, I’m just writing them down the best way I can right now so I can continue based on what I already have. Read on with a good amount of suspicion. :-)

The tl;dr is that `group` on `flatAlt` yields an object that preferrably renders as the second argument of `flatAlt`.

`layoutPretty` does a lookup whether *the first line* of the remaining document renders nicely; if yes, it chooses the preferred solution, otherwise it falls back to the fallback. `layoutSmart` does a similar thing, but with more lookahead.

What happens now in the concrete example you gave,

```
> x = group (flatAlt "Default" "Fallback")
> d = "/" <> align (cat [x, x, "Too wide!!!"])
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ d
/Default
 Fallback
 Too wide!!!
```

is that `layoutSmart` looks all the way down to the end of the document, decides that the »Too wide…« does not fit, and introduces the fallback twice. `layoutPretty` does less lookahead, and falls back differently.

In other words, this does not really have anything to do with `align`, but with the repeated call of group on `flatAlt` (since `cat` contains a group, and so does the contained `x`).

**Comment by sjakobi** [comment] 2019-10-18 16:55
> If I got it right, `group (flatAlt "A" "B")` is simply `Union "B" (flatAlt "A" "B")`.

That's right. You can easily check this by using a derived `Show` instance for `Doc`. Import `Text.Show.Function` to get an instance for the functions in `Doc`.

> `layoutSmart` looks all the way down to the end of the document, decides that the »Too wide…« does not fit, and introduces the fallback twice.

I'm not quite sure what you mean by "introducing the fallback twice". How does this explain the inconsistent behaviour for the first and the second `align`ed element?


> In other words, this does not really have anything to do with `align`

If you remove the `align`, the inconsistency actually goes away!

```
> d = "/" <> cat [x, x, "Too wide!!!"]
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ d
/Fallback
Fallback
Too wide!!!
```

**Comment by sjakobi** [comment] 2019-10-20 00:41
What also seems significant is that no matter how many identical elements you align, it is always only the first one that gets the default formatting:

```haskell
> mkD n = "/" <> align (cat (replicate n x ++ ["Too wide!!!"]))
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ mkD 1
/Default
 Too wide!!!
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ mkD 4
/Default
 Fallback
 Fallback
 Fallback
 Too wide!!!
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ mkD 10
/Default
 Fallback
 Fallback
 Fallback
 Fallback
 Fallback
 Fallback
 Fallback
 Fallback
 Fallback
 Too wide!!!

**Comment by sjakobi** [comment] 2019-10-20 02:24
Ha, turns out that we don't need `align` to reproduce the issue – `Nest` is sufficient:

```haskell
> mkD' n = Nest 1 (cat (replicate n x ++ ["Too wide!!!"]))
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ mkD' 2
Default
 Fallback
 Too wide!!!

**Comment by sjakobi** [comment] 2019-10-20 14:07
The outer `group` of `cat` is also unnecessary:

```haskell
> mkD' n = Nest 1 (vcat (replicate n x ++ ["Too wide!!!"]))
> mkD' 2
Nest 1 
    ( Cat 
        ( Union ( Text 8 "Fallback" ) 
            ( FlatAlt ( Text 7 "Default" ) ( Text 8 "Fallback" ) )
        ) 
        ( Cat ( FlatAlt Line Empty ) 
            ( Cat 
                ( Union ( Text 8 "Fallback" ) 
                    ( FlatAlt ( Text 7 "Default" ) ( Text 8 "Fallback" ) )
                ) 
                ( Cat ( FlatAlt Line Empty ) ( Text 11 "Too wide!!!" ) )
            )
        )
    )
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ mkD' 2
Default
 Fallback
 Too wide!!!

**Comment by sjakobi** [comment] 2019-10-20 21:10
Nor do we need the optional `Line`s:

```haskell
> d = Nest 1 $ x <> Line <> x <> Line <> "Too wide!!!"
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ d
Default
 Fallback
 Too wide!!!
```

**Comment by sjakobi** [comment] 2019-10-22 15:02
`ansi-wl-pprint` behaves the same way:

```haskell
> x = group (flatAlt "Default" "Fallback")
> d = Nest 1 $ x <> Line <> x <> Line <> "Too wide!!!"
> s = renderSmart 1 10 d
> displayIO stdout s
Default
 Fallback
 Too wide!!!

**Comment by quchen** [comment] 2019-10-23 08:28
I think this is a property of the (extended) WL algorithm. Unfortunately, I can’t really pin down the root of the issue to even figure out how to change it! I’ll keep looking…

**Comment by sjakobi** [comment] 2019-10-23 15:09
I have done some print debugging with `Debug.Trace` on [this branch](https://github.com/sjakobi/prettyprinter/tree/83-inconsistent-align).

When we layout `Nest 1 $ x <> Line <> x <> Line <> "Too wide!!!"` from https://github.com/quchen/prettyprinter/issues/83#issuecomment-544292972, `selectNicer` is called a total of three times.

In this first call, I actually don't understand why `x` `fits` and is therefore selected:

```
selectNicer:
  lineIndent:    1
  currentColumn: 1
  x:             SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  y:             SText 7 "Default" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  selected:      x
```

Just before returning the final `SimpleDocStream`, we have another two calls: The first one with the same arguments as above:

```
selectNicer:
  lineIndent:    1
  currentColumn: 1
  x:             SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  y:             SText 7 "Default" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  selected:      x
```

The second one decides on the final layout, and it seems to me that the "question" is already stacked us! `y` wouldn't fit either, but since it is the second alternative, it is what we return.

```
selectNicer:
  lineIndent:    0
  currentColumn: 0
  x:             SText 8 "Fallback" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
  y:             SText 7 "Default" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
  selected:      y
```

Here is the full log, including trace output from `best`:

<details>

```
λ> x = group (flatAlt "Default" "Fallback")
λ> d = Nest 1 $ x <> Line <> x <> Line <> "Too wide!!!"
λ> layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ d
best:
  nesting level:  0
  current column: 0
  i[ndendation]:  0
  d:              Nest 1 (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!")))))
  ds:             Nil
best:
  nesting level:  0
  current column: 0
  i[ndendation]:  1
  d:              Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!"))))
  ds:             Nil
best:
  nesting level:  0
  current column: 0
  i[ndendation]:  1
  d:              Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))
  ds:             Cons 1 (Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!")))) Nil
best:
  nesting level:  0
  current column: 0
  i[ndendation]:  1
  d:              Text 8 "Fallback"
  ds:             Cons 1 (Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!")))) Nil
best:
  nesting level:  0
  current column: 8
  i[ndendation]:  1
  d:              Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!")))
  ds:             Nil
best:
  nesting level:  0
  current column: 8
  i[ndendation]:  1
  d:              Line
  ds:             Cons 1 (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!"))) Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!"))
  ds:             Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 8 "Fallback"
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 9
  i[ndendation]:  1
  d:              Cat Line (Text 11 "Too wide!!!")
  ds:             Nil
best:
  nesting level:  1
  current column: 9
  i[ndendation]:  1
  d:              Line
  ds:             Cons 1 (Text 11 "Too wide!!!") Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 11 "Too wide!!!"
  ds:             Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              FlatAlt (Text 7 "Default") (Text 8 "Fallback")
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 7 "Default"
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 8
  i[ndendation]:  1
  d:              Cat Line (Text 11 "Too wide!!!")
  ds:             Nil
best:
  nesting level:  1
  current column: 8
  i[ndendation]:  1
  d:              Line
  ds:             Cons 1 (Text 11 "Too wide!!!") Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 11 "Too wide!!!"
  ds:             Nil
selectNicer:
  lineIndent:    1
  currentColumn: 1
  x:             SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  y:             SText 7 "Default" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  selected:      x
best:
  nesting level:  0
  current column: 0
  i[ndendation]:  1
  d:              FlatAlt (Text 7 "Default") (Text 8 "Fallback")
  ds:             Cons 1 (Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!")))) Nil
best:
  nesting level:  0
  current column: 0
  i[ndendation]:  1
  d:              Text 7 "Default"
  ds:             Cons 1 (Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!")))) Nil
best:
  nesting level:  0
  current column: 7
  i[ndendation]:  1
  d:              Cat Line (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!")))
  ds:             Nil
best:
  nesting level:  0
  current column: 7
  i[ndendation]:  1
  d:              Line
  ds:             Cons 1 (Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!"))) Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Cat (Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))) (Cat Line (Text 11 "Too wide!!!"))
  ds:             Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Union (Text 8 "Fallback") (FlatAlt (Text 7 "Default") (Text 8 "Fallback"))
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 8 "Fallback"
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 9
  i[ndendation]:  1
  d:              Cat Line (Text 11 "Too wide!!!")
  ds:             Nil
best:
  nesting level:  1
  current column: 9
  i[ndendation]:  1
  d:              Line
  ds:             Cons 1 (Text 11 "Too wide!!!") Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 11 "Too wide!!!"
  ds:             Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              FlatAlt (Text 7 "Default") (Text 8 "Fallback")
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 7 "Default"
  ds:             Cons 1 (Cat Line (Text 11 "Too wide!!!")) Nil
best:
  nesting level:  1
  current column: 8
  i[ndendation]:  1
  d:              Cat Line (Text 11 "Too wide!!!")
  ds:             Nil
best:
  nesting level:  1
  current column: 8
  i[ndendation]:  1
  d:              Line
  ds:             Cons 1 (Text 11 "Too wide!!!") Nil
best:
  nesting level:  1
  current column: 1
  i[ndendation]:  1
  d:              Text 11 "Too wide!!!"
  ds:             Nil
selectNicer:
  lineIndent:    1
  currentColumn: 1
  x:             SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  y:             SText 7 "Default" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
  selected:      x
selectNicer:
  lineIndent:    0
  currentColumn: 0
  x:             SText 8 "Fallback" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
  y:             SText 7 "Default" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
  selected:      y
SText 7 "Default" 
    ( SLine 1 
        ( SText 8 "Fallback" 
            ( SLine 1 ( SText 11 "Too wide!!!" SEmpty ) )
        )
    )
```
</details>

**Comment by sjakobi** [comment] 2019-10-23 15:26
On a whim, I changed the `min` in `minNestingLevel` to `max`:

https://github.com/quchen/prettyprinter/blob/27d56342d30879bb5c60c2c1af2eacf01c0a48a2/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1788

This does fix the layout for ` " " <> Nest 1 (x <> Line <> x <> Line <> "Too wide!!!")` and the old

```
> e = list []
> d = list [ align (list [ e, e, list [ e ] ]) ]
```

But it breaks this doctest:

```
src/Data/Text/Prettyprint/Doc/Internal.hs:1692: failure in expression `go layoutSmart doc'
expected: |------------------------|
          fun(
            fun(
              fun(
                fun(
                  fun(
                    [ abcdef
                    , ghijklm ])))))
          |------------------------|
 but got: |------------------------|
          fun(
            fun(
              fun(
                fun(
                  fun([ abcdef
                      , ghijklm ])))))
          |------------------------|

Examples: 247  Tried: 247  Errors: 0  Failures: 1
```

The rest of the testsuite actually passes!

**Comment by sjakobi** [comment] 2019-10-23 17:35
The `min`-`max` change actually seems to work very well for `dhall`! [Here](https://github.com/vmchale/cpkg/commit/6e59a9a3066daf81f33e1fb4afd521110da4ec17)'s what it does to a (very) large Dhall configuration.

**Comment by sjakobi** [comment] 2019-10-24 21:18
> In this first call, I actually don't understand why `x` `fits` and is therefore selected:
> 
> ```
> selectNicer:
>   lineIndent:    1
>   currentColumn: 1
>   x:             SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
>   y:             SText 7 "Default" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
>   selected:      x
> ```

I added some tracing on `layoutSmart`'s `fits` to answer my questions. For this call to fits, I get

```
fits
  minNesting: 1
  w[idth]   : 9
  sds       : SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
fits
  minNesting: 1
  w[idth]   : 1
  sds       : SLine 1 (SText 11 "Too wide!!!" SEmpty)
```

`fits` returns `True` at this point, because of this guard:

https://github.com/quchen/prettyprinter/blob/4d51362d7ea8bca0fe9e7ffec2ccd8fcd0065c0d/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1732-L1734

Since the `i[ndentation]` of the next line (1) is not deeper than the `m[inNesting]` (also 1), `fits` is satisfied, having checked only the very first line.

> The second one decides on the final layout, and it seems to me that the "question" is already stacked against us! `y` wouldn't fit either, but since it is the second alternative, it is what we return.
> 
> ```
> selectNicer:
>   lineIndent:    0
>   currentColumn: 0
>   x:             SText 8 "Fallback" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
>   y:             SText 7 "Default" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
>   selected:      y
> ```

In this case, since the following lines are indented more deeply than the minimum nesting level which is computed as `min lineIndent currentColumn = 0`, `fits` continues to the end of `x` and must discover that `"Too wide!!!"` is too wide!

It seems to me that this is not a great way of deciding the layout of the first line: None of the alternatives fit, but that's due to the remaining lines not fitting, not this one! Changing this seems to require a fairly fundamental change to the algorithm, so I haven't looked into it further.

**Comment by sjakobi** [comment] 2019-10-24 21:41
The return to the original problem with `align`, we need to look at situations where all lines have the same indentation (note the prepended space before `Nest 1`):

```haskell
> x = group (flatAlt "Default" "Fallback")
> d = "/" <> Nest 1 (x <> Line <> x <> Line <> "Too wide!!!")
> putStrLn $ renderString $ layoutSmart (LayoutOptions (AvailablePerLine 10 1)) $ d
/Default
 Fallback
 Too wide!!!
```

Here's the final call to `selectNicer` now:

```
selectNicer:
  lineIndent:    0
  currentColumn: 1
  x:             SText 8 "Fallback" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
  y:             SText 7 "Default" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
  selected:      y
```

Note that `currentColumn` is 1. `minNesting` as `min lineIndent currentColumn` is still 0 though, so we get this trace from `fits`:

```
fits
  minNesting: 0
  w[idth]   : 9
  sds       : SText 8 "Fallback" (SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))))
fits
  minNesting: 0
  w[idth]   : 1
  sds       : SLine 1 (SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty)))
fits
  minNesting: 0
  w[idth]   : 9
  sds       : SText 8 "Fallback" (SLine 1 (SText 11 "Too wide!!!" SEmpty))
fits
  minNesting: 0
  w[idth]   : 1
  sds       : SLine 1 (SText 11 "Too wide!!!" SEmpty)
fits
  minNesting: 0
  w[idth]   : 9
  sds       : SText 11 "Too wide!!!" SEmpty
fits
  minNesting: 0
  w[idth]   : -2
  sds       : SEmpty
```

Again, since the following lines are indented more deeply, we check all of them, discovering that they don't fit.

This explains the inconsistent formatting: While the first line starts on the same column as the remaining ones, its `lineIndent` is less, which causes `fits` to take the following lines into account too!

**Comment by sjakobi** [comment] 2019-10-24 22:00
So in order to layout the first `Nest`ed line on its own, we could try to adjust the minimum nesting level so its not less than the indentation of the following lines.  Computing `minNesting` as `max lineIndent currentColumn` or just `currentColumn` as this invariant would allow, is too simple though!

https://github.com/quchen/prettyprinter/blob/4d51362d7ea8bca0fe9e7ffec2ccd8fcd0065c0d/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1751

As we saw on the example of the doctest in https://github.com/quchen/prettyprinter/issues/83#issuecomment-545499436, we may want to optionally indent the `Nest`ed block _less_ than the current column! Such a layout would be prevented by a `minNesting` equal to the current column at the beginning of `Nest`.

**Comment by sjakobi** [comment] 2019-10-24 23:16
> Such a layout would be prevented by a `minNesting` equal to the current column at the beginning of `Nest`.

I actually don't quite understand why though. Will have to trace this too…

**Comment by sjakobi** [comment] 2019-10-25 13:13
To understand why computing `minNesting` as `(max lineIndent currentColumn)` breaks the [the "fun"-doctest](https://github.com/quchen/prettyprinter/blob/4d51362d7ea8bca0fe9e7ffec2ccd8fcd0065c0d/prettyprinter/src/Data/Text/Prettyprint/Doc/Internal.hs#L1667-L1676), I've traced the following reduced example, because the trace for the original is just too huge:

```haskell
> let fun x = hang 2 ("fun(" <> softline' <> x) <> ")"
> let doc = (fun . fun) (align (list ["abcdef", "ghijklm"]))
> let go layouter x = (T.putStrLn . renderStrict . layouter (LayoutOptions (AvailablePerLine 17 1))) x
> go layoutPretty doc
fun(fun([ abcdef
        , ghijklm ]))
> go layoutSmart doc
fun(
  fun(
    [ abcdef
    , ghijklm ]))
```

Again the difference between computing `minNestingLevel` as `(min lineIndent currentColumn)` vs. `(max lineIndent currentColumn)` becomes most evident in the very last two calls to `selectNicer`. In both variants the second last call to `selectNicer` has the following arguments:

```
selectNicer:
  lineIndent:    2
  currentColumn: 6
  x:             SText 2 "[ " (SText 6 "abcdef" (SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))))))
  y:             SLine 4 (SText 2 "[ " (SText 6 "abcdef" (SLine 4 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty))))))))
 ```

In the `max`-version we get the following trace from `fits`:

```
fits
  minNesting: 6
  w[idth]   : 11
  sds       : SText 2 "[ " (SText 6 "abcdef" (SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))))))
fits
  minNesting: 6
  w[idth]   : 9
  sds       : SText 6 "abcdef" (SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty))))))
fits
  minNesting: 6
  w[idth]   : 3
  sds       : SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))))
```

With a `minNesting` of 6, the `m[inNesting] < i[ndentation]` guard fails at `SLine 6` and we can return `True` early, having checked only the first line.

In the `min`-version, we can't stop so early, and end up discovering that the second line doesn't fit. So we choose the alternative, hanging layout (note that `y` starts with `SLine 4`).

```
fits
  minNesting: 2
  w[idth]   : 11
  sds       : SText 2 "[ " (SText 6 "abcdef" (SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))))))
fits
  minNesting: 2
  w[idth]   : 9
  sds       : SText 6 "abcdef" (SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty))))))
fits
  minNesting: 2
  w[idth]   : 3
  sds       : SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))))
fits
  minNesting: 2
  w[idth]   : 11
  sds       : SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty))))
fits
  minNesting: 2
  w[idth]   : 9
  sds       : SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))
fits
  minNesting: 2
  w[idth]   : 2
  sds       : SText 2 " ]" (SChar ')' (SChar ')' SEmpty))
fits
  minNesting: 2
  w[idth]   : 0
  sds       : SChar ')' (SChar ')' SEmpty)
fits
  minNesting: 2
  w[idth]   : -1
  sds       : SChar ')' SEmpty
```

This sets up the alternatives for the very last `selectNicer` step:


#### `max`:
```
selectNicer:
  lineIndent:    0
  currentColumn: 4
  x:             SText 4 "fun(" (SText 2 "[ " (SText 6 "abcdef" (SLine 8 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty))))))))
  y:             SLine 2 (SText 4 "fun(" (SText 2 "[ " (SText 6 "abcdef" (SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))))))))
  selected:      y
```

#### `min`:

```
selectNicer:
  lineIndent:    0
  currentColumn: 4
  x:             SText 4 "fun(" (SLine 6 (SText 2 "[ " (SText 6 "abcdef" (SLine 6 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty)))))))))
  y:             SLine 2 (SText 4 "fun(" (SLine 4 (SText 2 "[ " (SText 6 "abcdef" (SLine 4 (SText 2 ", " (SText 7 "ghijklm" (SText 2 " ]" (SChar ')' (SChar ')' SEmpty))))))))))
  selected:      y
```

I've attached the full traces:
* [max-small.log](https://github.com/quchen/prettyprinter/files/3772194/max-small.log)
* [min-small.log](https://github.com/quchen/prettyprinter/files/3772195/min-small.log)

**Comment by quchen** [comment] 2019-10-25 14:03
I’ll close this, since #89 seems to fix the issue, and this ticket has become quite large. Let’s continue the discussion there if necessary, or open a new ticket if the fix doesn’t work, to keep things a bit tidier.

**Closed by quchen** 2019-10-25 14:03 UTC
